In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf

In [5]:
data = pd.read_csv('daily_rv_hour_data.csv')

In [6]:
data

Unnamed: 0    AAPL.O    MSFT.O   GOOGL.O    GOOG.O    AMZN.O    NVDA.O  \
0    1/11/2023  0.000130  0.000072  0.000125  0.000110  0.000259  0.000196   
1    1/12/2023  0.000078  0.000201  0.000077  0.000065  0.000077  0.000959   
2    1/13/2023  0.000139  0.000079  0.000071  0.000065  0.000196  0.000579   
3    1/17/2023  0.000024  0.000043  0.000017  0.000020  0.000084  0.000118   
4    1/18/2023  0.000130  0.000188  0.000092  0.000109  0.000180  0.000234   
..         ...       ...       ...       ...       ...       ...       ...   
246   1/4/2024  0.000038  0.000028  0.000059  0.000049  0.000109  0.000132   
247   1/5/2024  0.000139  0.000075  0.000046  0.000044  0.000086  0.000254   
248   1/8/2024  0.000024  0.000044  0.000035  0.000036  0.000052  0.000183   
249   1/9/2024  0.000061  0.000054  0.000073  0.000064  0.000080  0.000658   
250  1/10/2024  0.000073  0.000059  0.000038  0.000036  0.000046  0.000183   

       META.O      BRKb    TSLA.O  ...    MDLZ.O    LRCX.O    REGN.O  \
0    0.000155  0.000047  0.000323  ...  0.000058  0.000287  0.000251   
1    0.000443  0.000018  0.000628  ...  0.000050  0.000540  0.000144   
2    0.000032  0.000009  0.001005  ...  0.000072  0.000113  0.000098   
3    0.000088  0.000028  0.000181  ...  0.000007  0.000153  0.000055   
4    0.000286  0.000099  0.000996  ...  0.000195  0.000339  0.000051   
..        ...       ...       ...  ...       ...       ...       ...   
246  0.000052  0.000038  0.000119  ...  0.000029  0.000140  0.000095   
247  0.000111  0.000018  0.000121  ...  0.000071  0.000107  0.000088   
248  0.000070  0.000048  0.000155  ...  0.000025  0.000055  0.000113   
249  0.000055  0.000010  0.000159  ...  0.000023  0.000064  0.000073   
250  0.000144  0.000024  0.000147  ...  0.000045  0.000175  0.000070   

          AMT       PGR     ADP.O       ETN       MMC     ADI.O        CB  
0    0.000092  0.000042  0.000038  0.000057  0.000039  0.000053  0.000019  
1    0.000229  0.000163  0.000083  0.000051  0.000088  0.000041  0.000069  
2    0.000039  0.000006  0.000054  0.000012  0.000044  0.000068  0.000038  
3    0.000134  0.000067  0.000099  0.000066  0.000019  0.000068  0.000012  
4    0.000368  0.000103  0.000069  0.000254  0.000123  0.000105  0.000126  
..        ...       ...       ...       ...       ...       ...       ...  
246  0.000210  0.000174  0.000012  0.000102  0.000010  0.000080  0.000068  
247  0.000187  0.000066  0.000017  0.000040  0.000062  0.000069  0.000025  
248  0.000071  0.000082  0.000009  0.000074  0.000048  0.000007  0.000042  
249  0.000149  0.000046  0.000039  0.000056  0.000018  0.000093  0.000034  
250  0.000159  0.000091  0.000007  0.000013  0.000023  0.000018  0.000036  

[251 rows x 101 columns]

In [7]:
data = data.rename(columns={"Unnamed: 0": "Date"})

In [8]:
import datetime

def str_to_datetime(s):
  split = s.split('/')
  month, day, year = int(split[0]), int(split[1]), int(split[2])
  return datetime.datetime(year=year, month=month, day=day)

datetime_object = str_to_datetime('1/10/2024')
datetime_object

datetime.datetime(2024, 1, 10, 0, 0)

In [9]:
data['Date'] = data['Date'].apply(str_to_datetime)
data['Date']

0     2023-01-11
1     2023-01-12
2     2023-01-13
3     2023-01-17
4     2023-01-18
         ...    
246   2024-01-04
247   2024-01-05
248   2024-01-08
249   2024-01-09
250   2024-01-10
Name: Date, Length: 251, dtype: datetime64[ns]

In [10]:
data.index = data.pop('Date')
data

AAPL.O    MSFT.O   GOOGL.O    GOOG.O    AMZN.O    NVDA.O  \
Date                                                                     
2023-01-11  0.000130  0.000072  0.000125  0.000110  0.000259  0.000196   
2023-01-12  0.000078  0.000201  0.000077  0.000065  0.000077  0.000959   
2023-01-13  0.000139  0.000079  0.000071  0.000065  0.000196  0.000579   
2023-01-17  0.000024  0.000043  0.000017  0.000020  0.000084  0.000118   
2023-01-18  0.000130  0.000188  0.000092  0.000109  0.000180  0.000234   
...              ...       ...       ...       ...       ...       ...   
2024-01-04  0.000038  0.000028  0.000059  0.000049  0.000109  0.000132   
2024-01-05  0.000139  0.000075  0.000046  0.000044  0.000086  0.000254   
2024-01-08  0.000024  0.000044  0.000035  0.000036  0.000052  0.000183   
2024-01-09  0.000061  0.000054  0.000073  0.000064  0.000080  0.000658   
2024-01-10  0.000073  0.000059  0.000038  0.000036  0.000046  0.000183   

              META.O      BRKb    TSLA.O       LLY  ...    MDLZ.O    LRCX.O  \
Date                                                ...                       
2023-01-11  0.000155  0.000047  0.000323  0.000123  ...  0.000058  0.000287   
2023-01-12  0.000443  0.000018  0.000628  0.000056  ...  0.000050  0.000540   
2023-01-13  0.000032  0.000009  0.001005  0.000020  ...  0.000072  0.000113   
2023-01-17  0.000088  0.000028  0.000181  0.000054  ...  0.000007  0.000153   
2023-01-18  0.000286  0.000099  0.000996  0.000125  ...  0.000195  0.000339   
...              ...       ...       ...       ...  ...       ...       ...   
2024-01-04  0.000052  0.000038  0.000119  0.000345  ...  0.000029  0.000140   
2024-01-05  0.000111  0.000018  0.000121  0.000147  ...  0.000071  0.000107   
2024-01-08  0.000070  0.000048  0.000155  0.000225  ...  0.000025  0.000055   
2024-01-09  0.000055  0.000010  0.000159  0.000067  ...  0.000023  0.000064   
2024-01-10  0.000144  0.000024  0.000147  0.000032  ...  0.000045  0.000175   

              REGN.O       AMT       PGR     ADP.O       ETN       MMC  \
Date                                                                     
2023-01-11  0.000251  0.000092  0.000042  0.000038  0.000057  0.000039   
2023-01-12  0.000144  0.000229  0.000163  0.000083  0.000051  0.000088   
2023-01-13  0.000098  0.000039  0.000006  0.000054  0.000012  0.000044   
2023-01-17  0.000055  0.000134  0.000067  0.000099  0.000066  0.000019   
2023-01-18  0.000051  0.000368  0.000103  0.000069  0.000254  0.000123   
...              ...       ...       ...       ...       ...       ...   
2024-01-04  0.000095  0.000210  0.000174  0.000012  0.000102  0.000010   
2024-01-05  0.000088  0.000187  0.000066  0.000017  0.000040  0.000062   
2024-01-08  0.000113  0.000071  0.000082  0.000009  0.000074  0.000048   
2024-01-09  0.000073  0.000149  0.000046  0.000039  0.000056  0.000018   
2024-01-10  0.000070  0.000159  0.000091  0.000007  0.000013  0.000023   

               ADI.O        CB  
Date                            
2023-01-11  0.000053  0.000019  
2023-01-12  0.000041  0.000069  
2023-01-13  0.000068  0.000038  
2023-01-17  0.000068  0.000012  
2023-01-18  0.000105  0.000126  
...              ...       ...  
2024-01-04  0.000080  0.000068  
2024-01-05  0.000069  0.000025  
2024-01-08  0.000007  0.000042  
2024-01-09  0.000093  0.000034  
2024-01-10  0.000018  0.000036  

[251 rows x 100 columns]

In [12]:
def df_to_X_Y(df, window_size=5):
  df_as_np = df.to_numpy()
  X = []
  y = []
  for i in range(len(df_as_np)-window_size):
    row = [r for r in df_as_np[i:i+window_size]]
    X.append(row)
    label = [df_as_np[i+window_size]]
    y.append(label)
  return np.array(X), np.array(y)

In [13]:
X, Y = df_to_X_Y(data)
X.shape, Y.shape

((246, 5, 100), (246, 1, 100))

In [14]:
q_80 = int(len(data.index) * .8)
q_90 = int(len(data.index) * .9)

X_train, Y_train =  X[:q_80], Y[:q_80]

X_val, Y_val =  X[q_80:q_90], Y[q_80:q_90]
X_test, Y_test =  X[q_90:], Y[q_90:]

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

model = Sequential([layers.Input((5, 100)),
                    layers.LSTM(64),
                    layers.Dense(32, activation='relu'),
                    layers.Dense(100)])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape              ┃    Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 64)                │     42,240 │
├─────────────────────────────────┼───────────────────────────┼────────────┤
│ dense (Dense)                   │ (None, 32)                │      2,080 │
├─────────────────────────────────┼───────────────────────────┼────────────┤
│ dense_1 (Dense)                 │ (None, 100)               │      3,300 │
└─────────────────────────────────┴───────────────────────────┴────────────┘

 Total params: 47,620 (186.02 KB)

 Trainable params: 47,620 (186.02 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
from keras import ops

def qlike(y_true, y_pred):
    sum = ops.log(y_pred+1e-16) + y_true/y_pred
    return ops.mean(sum, axis=-1)  # Note the `axis=-1`

In [25]:
model.compile(loss='mse', 
              optimizer=Adam(learning_rate=0.001),
              metrics=['mean_absolute_error'])

In [26]:
model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 4s 75ms/step - loss: 9.2096e-05 - mean_absolute_error: 0.0078 - val_loss: 2.2855e-05 - val_mean_absolute_error: 0.0034
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9196e-05 - mean_absolute_error: 0.0032 - val_loss: 5.6269e-06 - val_mean_absolute_error: 0.0018
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.2911e-06 - mean_absolute_error: 0.0018 - val_loss: 3.2256e-06 - val_mean_absolute_error: 0.0015
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.3221e-06 - mean_absolute_error: 0.0015 - val_loss: 2.0671e-06 - val_mean_absolute_error: 0.0012
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.9374e-06 - mean_absolute_error: 0.0011 - val_loss: 1.1612e-06 - val_mean_absolute_error: 8.3099e-04
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0029e-06 - mean_absolute_error: 7.6362e-04 - val_loss: 5.4871e-07 - val_mean_absolute_error: 5.6210e-04
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - 

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9682e-08 - mean_absolute_error: 9.1032e-05 - val_loss: 1.1077e-08 - val_mean_absolute_error: 7.1850e-05
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6075e-08 - mean_absolute_error: 9.9622e-05 - val_loss: 1.2588e-08 - val_mean_absolute_error: 8.2964e-05
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2462e-08 - mean_absolute_error: 9.1475e-05 - val_loss: 1.2934e-08 - val_mean_absolute_error: 8.5294e-05
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0297e-08 - mean_absolute_error: 9.1262e-05 - val_loss: 1.2416e-08 - val_mean_absolute_error: 8.0906e-05
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3327e-08 - mean_absolute_error: 9.2041e-05 - val_loss: 1.2119e-08 - val_mean_absolute_error: 8.1560e-05
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1219e-08 - mean_absolute_error: 8.8054e-05 - val_loss: 1.2327e-08 - val_mean_absolute_error: 8.1716e-05
Epoch 48/100
7/7 ━━━━━━

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.7232e-08 - mean_absolute_error: 8.7290e-05 - val_loss: 1.1293e-08 - val_mean_absolute_error: 7.6315e-05
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.3674e-08 - mean_absolute_error: 9.0574e-05 - val_loss: 1.3745e-08 - val_mean_absolute_error: 8.9127e-05
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8566e-08 - mean_absolute_error: 9.0919e-05 - val_loss: 1.1670e-08 - val_mean_absolute_error: 7.5774e-05
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.1824e-08 - mean_absolute_error: 8.9046e-05 - val_loss: 1.1614e-08 - val_mean_absolute_error: 7.5643e-05
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8511e-08 - mean_absolute_error: 8.8068e-05 - val_loss: 1.1758e-08 - val_mean_absolute_error: 7.8832e-05
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9290e-08 - mean_absolute_error: 9.2543e-05 - val_loss: 1.0866e-08 - val_mean_absolute_error: 7.3371e-05
Epoch 89/100
7/7 ━━━━━━

In [32]:
mse = tf.keras.losses.MeanSquaredError()

In [35]:
mse(Y_test, test_predictions).numpy()

2.3670475e-08

In [66]:
def qlike(y_true, y_pred):
    np.log(test_predictions+1e-16) + test_predictions/Y_test

array([[8.48270720e-05, 1.67137012e-04, 1.71093270e-04, ...,
        1.00248493e-04, 1.80441886e-04, 7.03088008e-05],
       [1.05199986e-04, 1.51839573e-04, 1.94398686e-04, ...,
        9.93516296e-05, 2.11039558e-04, 7.64667057e-05],
       [9.84146027e-05, 1.69203151e-04, 1.93613581e-04, ...,
        1.15042552e-04, 2.19158828e-04, 7.02030957e-05],
       ...,
       [8.60624714e-05, 1.82907563e-04, 1.46467239e-04, ...,
        1.02913007e-04, 1.80015340e-04, 8.12932849e-05],
       [8.58871499e-05, 1.84466597e-04, 1.53634697e-04, ...,
        1.08074397e-04, 1.86899677e-04, 7.77342357e-05],
       [8.68068310e-05, 1.86811201e-04, 1.72326341e-04, ...,
        1.20007433e-04, 2.04991549e-04, 6.96508214e-05]], dtype=float32)

In [113]:
np.nanmean(np.log(test_predictions+1e-16) + test_predictions/Y_test)

C:\Users\anato\AppData\Local\Temp\ipykernel_14828\606683579.py:1: RuntimeWarning: invalid value encountered in log
  np.nanmean(np.log(test_predictions+1e-16) + test_predictions/Y_test)


-5.155738288227155

In [114]:
np.log(test_predictions)

C:\Users\anato\AppData\Local\Temp\ipykernel_14828\3834911963.py:1: RuntimeWarning: invalid value encountered in log
  np.log(test_predictions)


array([[-9.374896 , -8.696696 , -8.673302 , ..., -9.207858 , -8.620102 ,
        -9.5626135],
       [-9.159647 , -8.792686 , -8.545599 , ..., -9.2168455, -8.463465 ,
        -9.478655 ],
       [-9.226321 , -8.68441  , -8.549646 , ..., -9.070209 , -8.425714 ,
        -9.564118 ],
       ...,
       [-9.360437 , -8.606529 , -8.828709 , ..., -9.181626 , -8.622469 ,
        -9.417447 ],
       [-9.362476 , -8.5980425, -8.780933 , ..., -9.13269  , -8.584939 ,
        -9.462214 ],
       [-9.351826 , -8.585412 , -8.666121 , ..., -9.027957 , -8.492542 ,
        -9.572016 ]], dtype=float32)

In [79]:
test_predictions

array([[8.48270720e-05, 1.67137012e-04, 1.71093270e-04, ...,
        1.00248493e-04, 1.80441886e-04, 7.03088008e-05],
       [1.05199986e-04, 1.51839573e-04, 1.94398686e-04, ...,
        9.93516296e-05, 2.11039558e-04, 7.64667057e-05],
       [9.84146027e-05, 1.69203151e-04, 1.93613581e-04, ...,
        1.15042552e-04, 2.19158828e-04, 7.02030957e-05],
       ...,
       [8.60624714e-05, 1.82907563e-04, 1.46467239e-04, ...,
        1.02913007e-04, 1.80015340e-04, 8.12932849e-05],
       [8.58871499e-05, 1.84466597e-04, 1.53634697e-04, ...,
        1.08074397e-04, 1.86899677e-04, 7.77342357e-05],
       [8.68068310e-05, 1.86811201e-04, 1.72326341e-04, ...,
        1.20007433e-04, 2.04991549e-04, 6.96508214e-05]], dtype=float32)